version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "type:chore"
      - "deps:actions"
    commit-message:
      prefix: "chore"
      include: "scope"

  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "type:chore"
      - "deps:npm"
    commit-message:
      prefix: "chore"
      include: "scope"
